version: "3.9"
services:
  mysql:
    image: mysql:8.4
    container_name: auth-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123"          # root password
      MYSQL_DATABASE: "authdb"            # optional: auto-create DB
      MYSQL_ROOT_HOST: "%"                # allow root to connect from outside container
      TZ: "UTC"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../internal/db/migrations:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  mysql_data:
